//
//  ListUserContactsViewController.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListUserContactsDisplayLogic: class
{
    func displaySomething(viewModel: ListUserContacts.Something.ViewModel)
}

class ListUserContactsViewController: UIViewController, ListUserContactsDisplayLogic
{
    var interactor: ListUserContactsBusinessLogic?
    var router: (NSObjectProtocol & ListUserContactsRoutingLogic & ListUserContactsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ListUserContactsInteractor()
        let presenter = ListUserContactsPresenter()
        let router = ListUserContactsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    @IBOutlet weak var contactsTableView: UITableView!
    var displayedResult: [Item] = []

    func doSomething()
    {
        let request = ListUserContacts.Something.Request()
        interactor?.getContacts(request: request)
        
        contactsTableView.delegate = self
        contactsTableView.dataSource = self

    }
    
    func displaySomething(viewModel: ListUserContacts.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}


extension ListUserContactsViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.displayedResult.count
    }
    
    //Setup cell
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let displayedContact = self.displayedResult[indexPath.row]
        var cell = contactsTableView.dequeueReusableCell(withIdentifier: "ContactCell")
        if cell == nil {
          cell = UITableViewCell(style: .value1, reuseIdentifier: "ContactCell")
        }
        cell?.textLabel?.text = displayedContact.name
        cell?.detailTextLabel?.text = ""
        cell?.detailTextLabel?.alpha = 0.5
        return cell!
    }
    
    //Cell tapped
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
//        router?.routeToShowContactDetail()
    }
}
