//
//  ListUserContactsPresenter.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListUserContactsPresentationLogic
{
    func presentContacts(response: ListUserContacts.Something.Response)
}

class ListUserContactsPresenter: ListUserContactsPresentationLogic
{
    weak var viewController: ListUserContactsDisplayLogic?
    
    // MARK: Do something
    
    func presentContacts(response: ListUserContacts.Something.Response)
    {
        let viewModel = ListUserContacts.Something.ViewModel(displayedContacts: response.result.items)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
