//
//  UserContactDeatilInteractor.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserContactDeatilBusinessLogic
{
    func doSomething(request: UserContactDeatil.Something.Request)
}

protocol UserContactDeatilDataStore
{
    //var name: String { get set }
}

class UserContactDeatilInteractor: UserContactDeatilBusinessLogic, UserContactDeatilDataStore
{
    var presenter: UserContactDeatilPresentationLogic?
    var worker: UserContactDeatilWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: UserContactDeatil.Something.Request)
    {
        worker = UserContactDeatilWorker()
        worker?.doSomeWork()
        
        //let response = UserContactDeatil.Something.Response()
        //presenter?.presentSomething(detail: Detail)
    }
}
