//
//  UserContactDeatilPresenter.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserContactDeatilPresentationLogic
{
  func presentSomething(detail: Detail)
}

class UserContactDeatilPresenter: UserContactDeatilPresentationLogic
{
  weak var viewController: UserContactDeatilDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(detail: Detail)
  {
    let viewModel = UserContactDeatil.Something.ViewModel(detail: detail)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
