//
//  LoginPresenter.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentResult(response: Login.Data.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentResult(response: Login.Data.Response)
  {
    let viewModel = Login.Data.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
