//
//  LoginInteractor.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func login(user: String)
}

protocol LoginDataStore
{
    var loginResult: Result? { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var loginResult: Result?
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    func login(user: String)
    {
        worker = LoginWorker()
        worker?.login(user: user) { (response, error) -> Void in
            if response != nil {
                self.loginResult = response?.result
                self.presenter?.presentResult(response: response!)
            } else {
                print(error as Any)
            }
        }
    }
}
