//
//  LoginWorker.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class LoginWorker
{
    func login(user: String, completion: @escaping (Login.Data.Response?, Error?) -> ())
    {
        guard let secretUser = SecurityService.encrypt(text: user, salt: "") else {
            print("Error encrypting")
            return
        }
        
        let fullResource = "test-tecnico/search?rut=" + secretUser
        requestHandler.get(resource: fullResource).validate().responseJSON { response in
            switch response.result {
            case .success(_):
                do {
                    let parsedResponse = try JSONDecoder().decode(Login.Data.Response.self, from: response.data!)
                    completion(parsedResponse,nil)
                } catch let err {
                    completion(nil,err)
                }
            case .failure(let err):
                completion(nil,err)
            }
        }
    }
}
