//
//  LoginModels.swift
//  UserInfoApp
//
//  Created by Luis Zapata on 17-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum Data
    {
        struct Request
        {
        }
        struct Response : Decodable
        {
            var responseCode: Int?
            var description: String?
            var result: Result?
            
        }
        
        struct ViewModel
        {
        }
    }
}

struct Result : Decodable {
    var items: [Item]
}

struct Item : Decodable {
    var name: String?
    var detail: Detail?
}

struct Detail : Decodable {
    var email: String?
    var phone_number: String?
}
